# Generated by Django 5.0.4 on 2024-06-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patientreg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('photo', models.ImageField(default=None, max_length=250, null=True, upload_to='patient/')),
            ],
        ),
    ]
