# Generated by Django 5.0.4 on 2024-05-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientreg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientreg',
            old_name='number',
            new_name='phone',
        ),
    ]
