# Generated by Django 5.0.4 on 2024-05-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientreg', '0002_rename_number_patientreg_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientreg',
            old_name='doctor',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patientreg',
            old_name='hospital',
            new_name='password',
        ),
    ]
