# Generated by Django 5.0.4 on 2024-05-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientreg', '0003_rename_doctor_patientreg_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreg',
            name='photo',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='patient/'),
        ),
    ]
