# Generated by Django 5.0.4 on 2024-06-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientreg', '0004_patientreg_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreg',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
