# Generated by Django 5.0.4 on 2024-05-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospreg',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='hosp/'),
        ),
    ]
