# Generated by Django 5.0.4 on 2024-06-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospreg', '0002_alter_hospreg_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospreg',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
