# Generated by Django 5.0.4 on 2024-05-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('languages', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('contactNumber', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('medicalDegree', models.CharField(max_length=50)),
                ('licenseNumber', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('workplace', models.CharField(max_length=50)),
                ('workAddress', models.CharField(max_length=50)),
                ('workcontact', models.CharField(max_length=50)),
                ('workEmail', models.CharField(max_length=50)),
            ],
        ),
    ]
