# Generated by Django 5.0.4 on 2024-05-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docreg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docreg',
            old_name='fullname',
            new_name='name',
        ),
    ]
