# Generated by Django 5.0.4 on 2024-05-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docreg', '0002_rename_fullname_docreg_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docreg',
            old_name='name',
            new_name='fullname',
        ),
    ]
