# Generated by Django 5.0.4 on 2024-05-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docreg', '0003_rename_name_docreg_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docreg',
            old_name='workcontact',
            new_name='workContact',
        ),
    ]
