# Generated by Django 5.0.4 on 2024-05-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docreg', '0004_rename_workcontact_docreg_workcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='docreg',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
