# Generated by Django 5.0.4 on 2024-05-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docreg', '0005_docreg_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='docreg',
            name='photo',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
    ]
