# Generated by Django 5.0.4 on 2024-05-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docreg', '0006_docreg_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='docreg',
            name='available_friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docreg',
            name='available_monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docreg',
            name='available_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docreg',
            name='available_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docreg',
            name='available_thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docreg',
            name='available_tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docreg',
            name='available_wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docreg',
            name='friday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docreg',
            name='friday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docreg',
            name='monday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docreg',
            name='monday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docreg',
            name='saturday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docreg',
            name='saturday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docreg',
            name='sunday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docreg',
            name='sunday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docreg',
            name='thursday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docreg',
            name='thursday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docreg',
            name='tuesday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docreg',
            name='tuesday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docreg',
            name='wednesday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docreg',
            name='wednesday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
