# Generated by Django 5.0.4 on 2024-05-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docreg', '0007_docreg_available_friday_docreg_available_monday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docreg',
            old_name='friday_end_time',
            new_name='friday_end',
        ),
        migrations.RenameField(
            model_name='docreg',
            old_name='friday_start_time',
            new_name='friday_start',
        ),
        migrations.RenameField(
            model_name='docreg',
            old_name='monday_end_time',
            new_name='monday_end',
        ),
        migrations.RenameField(
            model_name='docreg',
            old_name='monday_start_time',
            new_name='monday_start',
        ),
        migrations.RenameField(
            model_name='docreg',
            old_name='saturday_end_time',
            new_name='saturday_end',
        ),
        migrations.RenameField(
            model_name='docreg',
            old_name='saturday_start_time',
            new_name='saturday_start',
        ),
        migrations.RenameField(
            model_name='docreg',
            old_name='sunday_end_time',
            new_name='sunday_end',
        ),
        migrations.RenameField(
            model_name='docreg',
            old_name='sunday_start_time',
            new_name='sunday_start',
        ),
        migrations.RenameField(
            model_name='docreg',
            old_name='thursday_end_time',
            new_name='thursday_end',
        ),
        migrations.RenameField(
            model_name='docreg',
            old_name='thursday_start_time',
            new_name='thursday_start',
        ),
        migrations.RenameField(
            model_name='docreg',
            old_name='tuesday_end_time',
            new_name='tuesday_end',
        ),
        migrations.RenameField(
            model_name='docreg',
            old_name='tuesday_start_time',
            new_name='tuesday_start',
        ),
        migrations.RenameField(
            model_name='docreg',
            old_name='wednesday_end_time',
            new_name='wednesday_end',
        ),
        migrations.RenameField(
            model_name='docreg',
            old_name='wednesday_start_time',
            new_name='wednesday_start',
        ),
        migrations.RemoveField(
            model_name='docreg',
            name='available_friday',
        ),
        migrations.RemoveField(
            model_name='docreg',
            name='available_monday',
        ),
        migrations.RemoveField(
            model_name='docreg',
            name='available_saturday',
        ),
        migrations.RemoveField(
            model_name='docreg',
            name='available_sunday',
        ),
        migrations.RemoveField(
            model_name='docreg',
            name='available_thursday',
        ),
        migrations.RemoveField(
            model_name='docreg',
            name='available_tuesday',
        ),
        migrations.RemoveField(
            model_name='docreg',
            name='available_wednesday',
        ),
    ]
