# Generated by Django 5.0.4 on 2024-06-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docreg', '0008_rename_friday_end_time_docreg_friday_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docreg',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
