# Generated by Django 5.0.4 on 2024-06-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docreg', '0009_alter_docreg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docreg',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
