# Generated by Django 5.0.4 on 2024-07-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='review/'),
        ),
    ]
